.TH XMLTEX 1
.SH NAME
xmltex, pdfxmltex \- xml non-validating parser in TeX
.SH SYNOPSIS
.B xmltex
.I "xml file"
.br
.B pdfxmltex
.I "xml file"
.SH DESCRIPTION
This manual page documents briefly the
.BR xmltex ,
and
.B pdfxmltex
commands.  This manual page was written for the Debian GNU/Linux
distribution because the original program does not have a manual page.
Instead, it has documentation in HTML and PS format in the
/usr/share/doc/xmltex directory.
.PP
.B xmltex
and
.B pdfxmltex
is a TeX XML parser able to transform XML documents into .dvi files.
xmltex knows nothing about your XML files.  It needs to load some
special macros files, usually with the .xmt extension.  A
configuration file, either named xmltex.cfg or \[rs]jobname.cfg, is
parsed.  An especially useful configuration command is
.I \[rs]xmltraceoff
which disables XML elements tracing.
.PP
.B xmltex
already knows about many XML schemata, such as TEI, TEI.2, MathML, SEC, HTML
and XSL-FO, the support for the latest being provided by the passivetex
package.
.SH "SEE ALSO"
The programs are documented fully in their own manual in the
/usr/share/doc/xmltex directory.
.br
.BR latex (1),
.BR tex (1)
.SH AUTHOR
This manual page was written by Fabien Ni\[~n]oles <fabien@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
